---
title: "Execute Code in the Blog Post"
date: 2023-11-10
draft: false
categories:
  - Web
tags:
  - web
---
:source-highlighter: rouge
:rouge-css: style
:rouge-style: pastie
:toc:
// Set toclevels to be at least your hugo [markup.tableOfContents.endLevel] configuration key
:toclevels: 4

== Background

https://www.jdoodle.com[JDoodle] provides an IDE plugin to let you interact and execute the code inside your page.

Simply, just include below tags: 
[source,html]
----
<div data-pym-src='https://www.jdoodle.com/plugin' 
   data-language="java" 
   data-version-index="4">
  <!--your code goes here-->
</div>
<script src="https://www.jdoodle.com/assets/jdoodle-pym.min.js" 
type="text/javascript"></script>
----

== Example
Let's try to execute below quiz on Java polymorphism and see if the result is what you expect.

{{< rawhtml >}}
<div data-pym-src='https://www.jdoodle.com/plugin' 
   data-language="java" 
   data-version-index="4">
public class PolymorphismQuiz {
    
    static class Vehicle{
      static String name = "Vehicle";
      int speed = 200;
      static String showMe(){
          return "I am a vehicle";
      }

      int getSpeed(){
        return this.speed;
      }

    }
    
    static class Car extends Vehicle{
      static String name = "Car";
      int speed = 70;
      static String showMe(){
          return "I am a Car";
      }

      int getSpeed(){
        return this.speed;
      }
    }
     
    
    public static void main (String[] args) {
        Vehicle myCar = new Car();

        System.out.println(myCar.name);
        System.out.println(myCar.getSpeed());
        System.out.println(myCar.showMe());
        
    }
}
</div>
<script src="https://www.jdoodle.com/assets/jdoodle-pym.min.js" type="text/javascript"></script>
{{< / rawhtml >}}




