---
title: "Java: Always Pass by Value "
date: 2023-10-24
draft: false
categories:
  - Java
tags:
  - java
  - immutability
---
:source-highlighter: rouge
:rouge-css: style
:rouge-style: pastie
:toc:
// Set toclevels to be at least your hugo [markup.tableOfContents.endLevel] configuration key
:toclevels: 4

== Background

When I heard that Java is always passed by value, I took the C/C++ way of thinking that changing the value inside a function would not take effective.
However, it is not as simple as that.
For Java, object is passed by the copied value of the reference(memory address), which means changing the object's attribute value inside a function would take effective since they points to the same memory address.
But if it is an immutable object like String, changing its value would create a new String object with different reference(memory address).
Therefore, the value inside a function would not take effective.

.Mental shortcuts:
. Primitives -> NOT effective
. Mutable Object -> effective
. Immutable Object ->  NOT effective

[source,java]
----
public static void main(String[] args) {
    String immutableStingExample = "abc";
    StringBuilder mutableStingExample = new StringBuilder("abc");
    System.out.println("Before function is called: ");
    System.out.println("immutableStingExample: "+ immutableStingExample);
    System.out.println("mutableStingExample: "+ mutableStingExample);
    doSomething(immutableStingExample, mutableStingExample);
    System.out.println("After function is called: ");
    System.out.println("immutableStingExample: "+ immutableStingExample);
    System.out.println("mutableStingExample: "+ mutableStingExample);
}
static void doSomething(String immutableStingExample, StringBuilder mutableStingExample){
    immutableStingExample = "xyz";
    mutableStingExample = mutableStingExample.
        replace(0, mutableStingExample.length(), "xyz");
}
----

Output:
----
Before function is called: 
immutableStingExample: abc
mutableStingExample: abc
After function is called: 
immutableStingExample: abc
mutableStingExample: xyz
----


== P.S.
I think that is one of the reasons why understanding the concept of immutability in Java is so important. 